steps:
- bash: |
    echo "Pipeline.Workspace                     : $PIPELINE_WORKSPACE"
    echo "SolutionName                           : $SOLUTIONNAME"
    echo "SonarQube.ProjectKey                   : $SONARQUBE_PROJECTKEY"
  displayName: Display pipeline variables
